// Generated by https://quicktype.io

export interface LoginData {
    correo: string;
    password: string;
}

export interface RegisterData {
    correo: string;
    password: string;
    nombre: string;
}

export interface LoginResponse {
    usuario: Usuario;
    token:   string;
}

export interface Usuario {
    rol:    string;
    estado: boolean;
    google: boolean;
    nombre: string;
    correo: string;
    uid:    string;
    img?: string;
}


//// Productos
// Generated by https://quicktype.io

export interface ProductsResponse {
    total:     number;
    productos: Producto[];
}

export interface Producto {
    precio:    number;
    _id:       string;
    nombre:    string;
    categoria: Categoria;
    usuario:   Categoria;
    img?:      string;
    cantidad?:number;
    descripcion?:string;
    radioValues?: { [key: number]: string; }; 
    guarnicion?: { [key: number]: string; };
    salsa?: { [key: number]: string; };
}




// Generated by https://quicktype.io

export interface CategoriesResponse {
    total:      number;
    categorias: Categoria[];
}

export interface Categoria {
    _id:     string;
    nombre:  string;
    usuario?: CreadoPor;
}

export interface CreadoPor {
    _id:    string;
    nombre: string;
}


//Reservas

// Generated by https://quicktype.io

export interface Reservas {
    cantidad: number;
    _id:      string;
    fecha:    string;
    pago: number;
    tipo:string;
    usuario:  Categoria;
    comentarios:string;
}

export interface ReservasResponse {
    total:     number;
    reservas: Reservas[];
}

// Generated by https://quicktype.io

export interface Reserva {
    total:    number;
    reservas: ReservaElement[];
}

export interface ReservaElement {
    cantidad: number;
    _id:      string;
    fecha:    string;
    usuario:  Usuario;
}

export interface Usuario {
    _id:    string;
    nombre: string;
}
 


// Generated by https://quicktype.io

export interface MenuReservas {
    _id:            string;
    reserva:        string;
    productos:      Producto1[];
    usuario:        Usuario;
    fecha_creacion: string;
}


export interface Producto1 {
    termino?: any;
    guarnicion?: any;
    salsa?:any;
    producto:  Producto;
    cantidad: number;
  
   // producto: string;
}


// Generated by https://quicktype.io

export interface MenuResponse {
    total:        number;
    menureservas: MenuReservas[];
}


// Generated by https://quicktype.io

export interface Favoritos {
    favorito: boolean;
    _id:      string;
    producto: Producto;
    usuario:  Usuario;
}

export interface FavoritosResponse {
    total:     number;
    favoritos: Favoritos[];
}